export 'languages.dart';

String? selectedLang = '';

String getString(String key) {
  if (selectedLang == 'it') {
    return italianLang[key] ?? key;
  }
  if (selectedLang == 'en') {
    return englishLang[key] ?? key;
  }
  if (selectedLang == 'hi') {
    return hindiLang[key] ?? key;
  }
  if (selectedLang == 'ro') {
    return romanianLang[key] ?? key;
  }
  if (selectedLang == 'es') {
    return spanishLang[key] ?? key;
  }
  if (selectedLang == 'ar') {
    return arabLang[key] ?? key;
  }
  if (selectedLang == 'sq') {
    return albanianLang[key] ?? key;
  }
  return ''; // actually this should never happen
}

Map<String, String> availableLanguages = {
  'it': 'Italiano',
  'en': 'English',
  'hi': 'हिन्दी',
  'ro': 'Română',
  'es': 'Español',
  'ar': 'عربى',
  'sq': 'Shqip',
};

Map<String, String> italianLang = {
  // misc
  'months': 'mesi',
  'and': 'e',
  'days': 'giorni',
  'cancel': 'Annulla',
  'total': 'Totale',
  'MyBTPInformationDeleteError': 'Per vendere un BTP vai al portafoglio.',
  'ExplorePageBTPInformationDeleteErrorButton': 'Chiudi',
  // header
  'appTopBarHome': 'simpleBTP',
  'appTopBarExplore': 'Esplora',
  'appTopBarWallet': 'Portafoglio',
  'appTopBarSettings': 'Impostazioni',
  'appTopBarPickLanguage': 'Seleziona lingua',
  // footer
  'appBottomBarHome': 'Home',
  'appBottomBarExplore': 'Esplora',
  'appBottomBarWallet': 'Portafoglio',
  'appBottomBarSettings': 'Impostazioni',
  // homepage
  'homeBalanceText': 'Il tuo investimento',
  'homeMyAssets': 'I tuoi migliori BTP',
  'homePageNoBTPsYet':
      "Non hai ancora comprato un BTP. Vai al portafoglio per comprarne uno.",
  'homeMyAssetsViewAllButton': 'Vedi tutti',
  'homeBestBTPs': 'I BTP più performanti',
  'homeBestBTPsViewAllButton': 'Vedi tutti',
  // walletpage
  'walletBalanceText': 'Il tuo investimento',
  'walletMyAssets': 'I tuoi asset',
  'walletPaysWhat': 'Paga',
  'walletPaysIn': 'in',
  'walletPageNoBTPsYet':
      'Per aggiungere un nuovo asset, premi il "+" nell\'angolo in alto a destra dello schermo.',
  'walletBalanceGraphOneWeekText': 'Sett',
  'walletBalanceGraphOneMonthText': 'Mese',
  'walletBalanceGraphThreeMonthsText': '3M',
  'walletBalanceGraphOneYearText': 'Anno',
  'walletBalanceGraphTenYearsText': '10A',
  'WalletPageBTPInformationBuyDate': 'Data di acquisto (debug)',
  'WalletPageBTPInformationBuyPrice': 'Prezzo di acquisto (debug)',
  'WalletPageBTPInformationProfitability': 'Profitto alla scadenza',
  'WalletPageBTPInformationProfitabilityNow': 'Profitto vendendo ora',
  'ExplorePageBTPInformationDeleteButton': 'Vendi questo BTP',
  // explorepage
  'exploreSearchPlaceholder': 'Cerca un BTP...',
  'explorePageResults': 'Risultati',
  'explorePageOrder': 'Ordine',
  'explorePageOrderByValue': 'Prezzo',
  'explorePageOrderByCedola': 'Cedola',
  'explorePageOrderByExpirationDate': 'Scadenza',
  'explorePageOrderByValueButton': 'Prezzo di mercato',
  'explorePageOrderByCedolaButton': 'Cedola annuale',
  'explorePageOrderByExpirationDateButton': 'Data di scadenza',
  'explorePageFilterTitle': 'Personalizza la tua ricerca',
  'explorePageValueFilterTitle': 'Prezzo di mercato',
  'explorePageCedolaFilterTitle': 'Cedola annuale',
  'explorePageExpirationDateFilterTitle': 'Data di scadenza',
  'explorePageApplyFiltersButton': 'Applica',
  'ExplorePageBTPChartTitle': 'Storico',
  'ExplorePageBTPInformationTitle': 'Informazioni BTP',
  'ExplorePageBTPInformationPrice': 'Prezzo',
  'ExplorePageBTPInformationCoupon': 'Cedola annuale',
  'ExplorePageBTPInformationExpirationDate': 'Data di scadenza',
  'ExplorePageBTPInformationISIN': 'Codice ISIN',
  'ExplorePageBTPInformationProfitability': 'Profitto acquistando ora',
  'ExplorePageBTPInformationDeleteConfirmationMessage':
      'Sei sicuro? Quest\'azione non può essere annullata.',
  'ExplorePageBTPInformationDeleteConfirmationCancelButton': 'Annulla',
  'ExplorePageBTPInformationDeleteConfirmationButton': 'Elimina',
  // settingspage
  'settingsPageAccountTitle': 'Account',
  'settingsPageWalletBackupButton': 'Backup portafoglio',
  'settingsPageWalletBackupRestoreButton': 'Ripristina backup portafoglio',
  'settingsPageWalletDeleteButton': 'Elimina portafoglio',
  'settingsPagePersonalizationTitle': 'Personalizzazione',
  'settingsPageDarkModeButton': 'Modalità scura',
  'settingsPageLanguageButton': 'Seleziona lingua',
  // addBTP
  'appTopBarAddBTP': 'Compra BTP',
  'addBTPSearchPlaceholder': 'Cerca un BTP...',
  'addBTPPageResults': 'Risultati',
  'addBTPPageOrder': 'Ordine',
  'addBTPPageOrderByValue': 'Prezzo',
  'addBTPPageOrderByCedola': 'Cedola',
  'addBTPPageOrderByExpirationDate': 'Scadenza',
  'addBTPPageOrderByValueButton': 'Prezzo di mercato',
  'addBTPPageOrderByCedolaButton': 'Cedola annuale',
  'addBTPPageOrderByExpirationDateButton': 'Data di scadenza',
  'addBTPPageFilterTitle': 'Personalizza la tua ricerca',
  'addBTPPageValueFilterTitle': 'Prezzo di mercato',
  'addBTPPageCedolaFilterTitle': 'Cedola annuale',
  'addBTPPageExpirationDateFilterTitle': 'Scadenza',
  'addBTPPageApplyFiltersButton': 'Apply',
  'addBTPPageDateSectionTitle': 'Data di acquisto',
  'addBTPPageSelectDateButton': 'Seleziona',
  'addBTPPagePriceSectionTitle': 'Prezzo di acquisto (singolo)',
  'addBTPPagePriceSectionPlaceholder': 'Prezzo di acquisto...',
  'addBTPPageInvestmentSectionTitle': 'Quantità di BTP',
  'addBTPPageInvestmentSectionPlaceholder': 'Quanti BTPs?',
  'addBTPPageAddButton': 'Compra questo BTP',
  'addBTPSecondPageBackButton': 'Seleziona BTP',
  'addBTPPageInvestmentTooLowError':
      'L\'investimento totale deve essere almeno 1000.',
  'addBTPPagePaymentMethodCancel': 'Annulla',
  'addBTPPagePaymentMethodTitle': 'Seleziona metodo di pagamento',
  'addBTPPagePaymentMethodMessage':
      'Ci siamo quasi! Seleziona il metodo di pagamento per completare l\'acquisto.',
  'addBTPPagePaymentMethodApplePay': 'Apple Pay',
  'addBTPPagePaymentMethodDebit': 'Carta di debito',
  'addBTPPagePaymentMethodPaypal': 'Paypal',
};

Map<String, String> englishLang = {
  // misc
  'months': 'months',
  'and': 'and',
  'days': 'days',
  'cancel': 'Cancel',
  'total': 'Total',
  'MyBTPInformationDeleteError': 'To delete a BTP please go to Wallet.',
  'ExplorePageBTPInformationDeleteErrorButton': 'Dismiss',
  // header
  'appTopBarHome': 'simpleBTP',
  'appTopBarExplore': 'Explore',
  'appTopBarWallet': 'Wallet',
  'appTopBarSettings': 'Settings',
  'appTopBarPickLanguage': 'Select language',
  // footer
  'appBottomBarHome': 'Home',
  'appBottomBarExplore': 'Explore',
  'appBottomBarWallet': 'Wallet',
  'appBottomBarSettings': 'Settings',
  // homepage
  'homeBalanceText': 'Your investment',
  'homeMyAssets': 'Your best BTPs',
  'homePageNoBTPsYet': "You didn't buy any BTPs yet. Go to Wallet to buy one.",
  'homeMyAssetsViewAllButton': 'View all',
  'homeBestBTPs': 'Best performing BTPs',
  'homeBestBTPsViewAllButton': 'View all',
  'homePageMyBTPSnackBar': 'To view all BTP information go to Wallet.',
  'homePageExploreBTPSnackBar': 'To view all BTP information go to Explore.',
  // walletpage
  'walletBalanceText': 'Your investment',
  'walletMyAssets': 'Your assets',
  'walletPaysWhat': 'Pays',
  'walletPaysIn': 'in',
  'walletPageNoBTPsYet':
      'To buy a new asset, press the "+" on the top-right corner of the screen.',
  'walletBalanceGraphOneWeekText': 'Week',
  'walletBalanceGraphOneMonthText': 'Month',
  'walletBalanceGraphThreeMonthsText': '3M',
  'walletBalanceGraphOneYearText': 'Year',
  'walletBalanceGraphTenYearsText': '10Y',
  'WalletPageBTPInformationBuyDate': 'Buy date',
  'WalletPageBTPInformationBuyPrice': 'Buy price',
  'WalletPageBTPInformationProfitability': 'Profit at expiration',
  'WalletPageBTPInformationProfitabilityNow': 'Profit selling now',
  'ExplorePageBTPInformationDeleteButton': 'Sell this BTP',
  // explorepage
  'exploreSearchPlaceholder': 'Search for a BTP...',
  'explorePageResults': 'Results',
  'explorePageOrder': 'Order',
  'explorePageOrderByValue': 'Price',
  'explorePageOrderByCedola': 'Coupon',
  'explorePageOrderByExpirationDate': 'Expiration',
  'explorePageOrderByValueButton': 'Market price',
  'explorePageOrderByCedolaButton': 'Yearly coupon',
  'explorePageOrderByExpirationDateButton': 'Expiration date',
  'explorePageFilterTitle': 'Customize your search',
  'explorePageValueFilterTitle': 'Market price',
  'explorePageCedolaFilterTitle': 'Yearly coupon',
  'explorePageExpirationDateFilterTitle': 'Expiration date',
  'explorePageApplyFiltersButton': 'Apply',
  'ExplorePageBTPChartTitle': 'Historical data',
  'ExplorePageBTPInformationTitle': 'BTP Information',
  'ExplorePageBTPInformationPrice': 'Price',
  'ExplorePageBTPInformationCoupon': 'Yearly coupon',
  'ExplorePageBTPInformationExpirationDate': 'Expiration date',
  'ExplorePageBTPInformationISIN': 'ISIN code',
  'ExplorePageBTPInformationProfitability': 'Profit buying now',
  'ExplorePageBTPInformationDeleteConfirmationMessage':
      'Are you sure? This action cannot be undone.',
  'ExplorePageBTPInformationDeleteConfirmationCancelButton': 'Cancel',
  'ExplorePageBTPInformationDeleteConfirmationButton': 'Delete',
  // settingspage
  'settingsPageAccountTitle': 'Account',
  'settingsPageWalletBackupButton': 'Backup wallet',
  'settingsPageWalletBackupRestoreButton': 'Restore wallet backup',
  'settingsPageWalletDeleteButton': 'Delete wallet',
  'settingsPagePersonalizationTitle': 'Personalization',
  'settingsPageDarkModeButton': 'Dark mode',
  'settingsPageLanguageButton': 'Select language',
  // addBTP
  'appTopBarAddBTP': 'Buy a BTP',
  'addBTPSearchPlaceholder': 'Search for a BTP...',
  'addBTPPageResults': 'Results',
  'addBTPPageOrder': 'Order',
  'addBTPPageOrderByValue': 'Price',
  'addBTPPageOrderByCedola': 'Coupon',
  'addBTPPageOrderByExpirationDate': 'Expiration',
  'addBTPPageOrderByValueButton': 'Market price',
  'addBTPPageOrderByCedolaButton': 'Yearly coupon',
  'addBTPPageOrderByExpirationDateButton': 'Expiration date',
  'addBTPPageFilterTitle': 'Customize your search',
  'addBTPPageValueFilterTitle': 'Market price',
  'addBTPPageCedolaFilterTitle': 'Yearly coupon',
  'addBTPPageExpirationDateFilterTitle': 'Expiration date',
  'addBTPPageApplyFiltersButton': 'Apply',
  'addBTPPageDateSectionTitle': 'Purchase date (debug)',
  'addBTPPageSelectDateButton': 'Select',
  'addBTPPagePriceSectionTitle': 'Purchase price (debug)',
  'addBTPPagePriceSectionPlaceholder': 'Purchase price...',
  'addBTPPageInvestmentSectionTitle': 'Investment quantity',
  'addBTPPageInvestmentSectionPlaceholder': 'How many BTPs?',
  'addBTPPageAddButton': 'Buy this BTP',
  'addBTPSecondPageBackButton': 'Select BTP',
  'addBTPPageInvestmentTooLowError': 'Total investment must be at least 1000.',
  'addBTPPagePaymentMethodCancel': 'Cancel',
  'addBTPPagePaymentMethodTitle': 'Select payment method',
  'addBTPPagePaymentMethodApplePay': 'Apple Pay',
  'addBTPPagePaymentMethodDebit': 'Debit Card',
  'addBTPPagePaymentMethodPaypal': 'Paypal',
  'addBTPPagePaymentMethodMessage':
      'Almost there! Select the payment method to complete the purchase.',
};

Map<String, String> hindiLang = {
  // misc
  'months': 'महीने',
  'and': 'और',
  'days': 'दिन',
  'cancel': 'रद्द करें',
  // header
  'appTopBarHome': 'होम',
  'appTopBarExplore': 'अन्वेषण',
  'appTopBarWallet': 'बटुआ',
  'appTopBarSettings': 'सेटिंग्स',
  'appTopBarPickLanguage': "यह बदलें",
  // footer
  'appBottomBarHome': 'होम',
  'appBottomBarExplore': 'अन्वेषण',
  'appBottomBarWallet': 'बटुआ',
  'appBottomBarSettings': 'सेटिंग्स',
  // homepage
  'homeBalanceText': 'आपका निवेश',
  'homeMyAssets': 'आपकी सर्वोत्तम BTP',
  'homeMyAssetsViewAllButton': 'सभी देखें',
  'homeBestBTPs': 'सर्वोत्तम BTP',
  'homeBestBTPsViewAllButton': 'सभी देखें',
  // walletpage
  'walletBalanceText': 'आपका निवेश',
  'walletMyAssets': 'आपके संपत्ति',
  'walletPaysWhat': 'भुगतान',
  'walletPaysIn': 'में',
  // explorepage
  'exploreSearchPlaceholder': 'किसी उपकरण की खोज करें...',
  'explorePageResults': 'परिणाम',
  'explorePageOrder': 'क्रम',
  'explorePageOrderByValue': 'मूल्य',
  'explorePageOrderByCedola': 'सेडोला',
  'explorePageOrderByExpirationDate': 'समाप्ति तिथि',
  'explorePageOrderByValueButton': 'बाजार मूल्य',
  'explorePageOrderByCedolaButton': 'वार्षिक सेडोला',
  'explorePageOrderByExpirationDateButton': 'समाप्ति तिथि',
  'explorePageFilterTitle': 'खोज को अनुकूलित करें',
  'explorePageValueFilterTitle': 'बाजार मूल्य',
  'explorePageCedolaFilterTitle': 'वार्षिक सेडोला',
  'explorePageExpirationDateFilterTitle': 'समाप्ति तिथि',
  'explorePageApplyFiltersButton': 'लागू करें',
  // settingspage
  'settingsPageAccountTitle': 'खाता',
  'settingsPageWalletBackupButton': 'बटुआ बैकअप',
  'settingsPageWalletBackupRestoreButton': 'बटुआ बैकअप बहाल करें',
  'settingsPageWalletDeleteButton': 'बटुआ हटाएं',
  'settingsPagePersonalizationTitle': 'व्यक्तिगतीकरण',
  'settingsPageDarkModeButton': 'डार्क मोड',
  'settingsPageLanguageButton': 'भाषा चुनें',
};

Map<String, String> romanianLang = {
  // misc
  'months': 'luni',
  'and': 'și',
  'days': 'zile',
  'cancel': 'Anulează',
  'MyBTPInformationDeleteError': 'Pentru a șterge un BTP, mergi la Portofel.',
  'ExplorePageBTPInformationDeleteErrorButton': 'Închide',
  // header
  'appTopBarHome': 'simpleBTP',
  'appTopBarExplore': 'Explorează',
  'appTopBarWallet': 'Portofel',
  'appTopBarSettings': 'Setări',
  'appTopBarPickLanguage': 'Selectează limba',
  // footer
  'appBottomBarHome': 'Acasă',
  'appBottomBarExplore': 'Explorează',
  'appBottomBarWallet': 'Portofel',
  'appBottomBarSettings': 'Setări',
  // homepage
  'homeBalanceText': 'Investiția ta',
  'homeMyAssets': 'Cele mai bune BTP-uri',
  'homePageNoBTPsYet':
      "Nu ai adăugat încă niciun BTP. Mergi la Portofel pentru a adăuga unul.",
  'homeMyAssetsViewAllButton': 'Vezi toate',
  'homeBestBTPs': 'Top BTP-uri',
  'homeBestBTPsViewAllButton': 'Vezi toate',
  // walletpage
  'walletBalanceText': 'Investiția ta',
  'walletMyAssets': 'Activele tale',
  'walletPaysWhat': 'Plătește',
  'walletPaysIn': 'în',
  'walletPageNoBTPsYet':
      'Pentru a adăuga un nou activ, apasă pe "+" din colțul din dreapta sus al ecranului.',
  'walletBalanceGraphOneWeekText': 'Săpt',
  'walletBalanceGraphOneMonthText': 'Lună',
  'walletBalanceGraphThreeMonthsText': '3L',
  'walletBalanceGraphOneYearText': 'An',
  'walletBalanceGraphTenYearsText': '10A',
  'WalletPageBTPInformationBuyDate': 'Data achiziției',
  'WalletPageBTPInformationBuyPrice': 'Prețul de achiziție',
  'WalletPageBTPInformationProfitability': 'Profit la scadență',
  'WalletPageBTPInformationProfitabilityNow': 'Profit vânzând acum',
  'ExplorePageBTPInformationDeleteButton': 'Șterge din portofel',
  // explorepage
  'exploreSearchPlaceholder': 'Caută un BTP..',
  'explorePageResults': 'Rezultate',
  'explorePageOrder': 'Ordine',
  'explorePageOrderByValue': 'Preț',
  'explorePageOrderByCedola': 'Cupon',
  'explorePageOrderByExpirationDate': 'Scadență',
  'explorePageOrderByValueButton': 'Preț de piață',
  'explorePageOrderByCedolaButton': 'Cupon anual',
  'explorePageOrderByExpirationDateButton': 'Data de scadență',
  'explorePageFilterTitle': 'Personalizează-ți căutarea',
  'explorePageValueFilterTitle': 'Preț de piață',
  'explorePageCedolaFilterTitle': 'Cupon anual',
  'explorePageExpirationDateFilterTitle': 'Data de scadență',
  'explorePageApplyFiltersButton': 'Aplică',
  'ExplorePageBTPChartTitle': 'Date istorice',
  'ExplorePageBTPInformationTitle': 'Informații BTP',
  'ExplorePageBTPInformationPrice': 'Preț',
  'ExplorePageBTPInformationCoupon': 'Cupon anual',
  'ExplorePageBTPInformationExpirationDate': 'Data de scadență',
  'ExplorePageBTPInformationISIN': 'Cod ISIN',
  'ExplorePageBTPInformationProfitability': 'Profit cumpărând acum',
  'ExplorePageBTPInformationDeleteConfirmationMessage':
      'Ești sigur? Această acțiune nu poate fi anulată.',
  'ExplorePageBTPInformationDeleteConfirmationCancelButton': 'Anulează',
  'ExplorePageBTPInformationDeleteConfirmationButton': 'Șterge',
  // settingspage
  'settingsPageAccountTitle': 'Cont',
  'settingsPageWalletBackupButton': 'Backup portofel',
  'settingsPageWalletBackupRestoreButton': 'Restaurează backup portofel',
  'settingsPageWalletDeleteButton': 'Șterge portofel',
  'settingsPagePersonalizationTitle': 'Personalizare',
  'settingsPageDarkModeButton': 'Mod întunecat',
  'settingsPageLanguageButton': 'Selectează limba',
  // addBTP
  'appTopBarAddBTP': 'Adaugă BTP',
  'addBTPSearchPlaceholder': '  Caută un BTP...',
  'addBTPPageResults': 'Rezultate',
  'addBTPPageOrder': 'Ordine',
  'addBTPPageOrderByValue': 'Preț',
  'addBTPPageOrderByCedola': 'Cupon',
  'addBTPPageOrderByExpirationDate': 'Scadență',
  'addBTPPageOrderByValueButton': 'Preț de piață',
  'addBTPPageOrderByCedolaButton': 'Cupon anual',
  'addBTPPageOrderByExpirationDateButton': 'Data de scadență',
  'addBTPPageFilterTitle': 'Personalizează căutarea',
  'addBTPPageValueFilterTitle': 'Preț de piață',
  'addBTPPageCedolaFilterTitle': 'Cupon anual',
  'addBTPPageExpirationDateFilterTitle': 'Scadență',
  'addBTPPageApplyFiltersButton': 'Aplică',
  'addBTPPageDateSectionTitle': 'Data de achiziție',
  'addBTPPageSelectDateButton': 'Selectează',
  'addBTPPagePriceSectionTitle': 'Preț de achiziție (singur)',
  'addBTPPagePriceSectionPlaceholder': 'Preț de achiziție...',
  'addBTPPageInvestmentSectionTitle': 'Cantitatea de BTP',
  'addBTPPageInvestmentSectionPlaceholder': 'Câte BTP-uri?',
  'addBTPPageAddButton': 'Adaugă la portofel',
  'addBTPSecondPageBackButton': 'Selectează BTP',
};

Map<String, String> spanishLang = {
  // misc
  'months': 'meses',
  'and': 'y',
  'days': 'días',
  'cancel': 'Cancelar',
  'MyBTPInformationDeleteError': 'Para eliminar un BTP, ve a la cartera.',
  'ExplorePageBTPInformationDeleteErrorButton': 'Descartar',
  // header
  'appTopBarHome': 'simpleBTP',
  'appTopBarExplore': 'Explorar',
  'appTopBarWallet': 'Cartera',
  'appTopBarSettings': 'Ajustes',
  'appTopBarPickLanguage': 'Seleccionar idioma',
  // footer
  'appBottomBarHome': 'Inicio',
  'appBottomBarExplore': 'Explorar',
  'appBottomBarWallet': 'Cartera',
  'appBottomBarSettings': 'Ajustes',
  // homepage
  'homeBalanceText': 'Tu inversión',
  'homeMyAssets': 'Tus mejores BTP',
  'homePageNoBTPsYet':
      "Aún no has añadido ningún BTP. Ve a la cartera para añadir uno.",
  'homeMyAssetsViewAllButton': 'Ver todos',
  'homeBestBTPs': 'Mejores BTP',
  'homeBestBTPsViewAllButton': 'Ver todos',
  // walletpage
  'walletBalanceText': 'Tu inversión',
  'walletMyAssets': 'Tus activos',
  'walletPaysWhat': 'Paga',
  'walletPaysIn': 'en',
  'walletPageNoBTPsYet':
      'Para añadir un nuevo activo, pulsa el "+" en la esquina superior derecha de la pantalla.',
  'walletBalanceGraphOneWeekText': 'Sem',
  'walletBalanceGraphOneMonthText': 'Mes',
  'walletBalanceGraphThreeMonthsText': '3M',
  'walletBalanceGraphOneYearText': 'Año',
  'walletBalanceGraphTenYearsText': '10A',
  'WalletPageBTPInformationBuyDate': 'Fecha de compra',
  'WalletPageBTPInformationBuyPrice': 'Precio de compra',
  'WalletPageBTPInformationProfitability': 'Beneficio a la expiración',
  'WalletPageBTPInformationProfitabilityNow': 'Beneficio vendiendo ahora',
  'ExplorePageBTPInformationDeleteButton': 'Eliminar de la cartera',
  // explorepage
  'exploreSearchPlaceholder': 'Buscar un BTP...',
  'explorePageResults': 'Resultados',
  'explorePageOrder': 'Orden',
  'explorePageOrderByValue': 'Precio',
  'explorePageOrderByCedola': 'Cupón',
  'explorePageOrderByExpirationDate': 'Expiración',
  'explorePageOrderByValueButton': 'Precio de mercado',
  'explorePageOrderByCedolaButton': 'Cupón anual',
  'explorePageOrderByExpirationDateButton': 'Fecha de expiración',
  'explorePageFilterTitle': 'Personaliza tu búsqueda',
  'explorePageValueFilterTitle': 'Precio de mercado',
  'explorePageCedolaFilterTitle': 'Cupón anual',
  'explorePageExpirationDateFilterTitle': 'Fecha de expiración',
  'explorePageApplyFiltersButton': 'Aplicar',
  'ExplorePageBTPChartTitle': 'Datos históricos',
  'ExplorePageBTPInformationTitle': 'Información BTP',
  'ExplorePageBTPInformationPrice': 'Precio',
  'ExplorePageBTPInformationCoupon': 'Cupón anual',
  'ExplorePageBTPInformationExpirationDate': 'Fecha de expiración',
  'ExplorePageBTPInformationISIN': 'Código ISIN',
  'ExplorePageBTPInformationProfitability': 'Beneficio comprando ahora',
  'ExplorePageBTPInformationDeleteConfirmationMessage':
      '¿Estás seguro? Esta acción no se puede deshacer.',
  'ExplorePageBTPInformationDeleteConfirmationCancelButton': 'Cancelar',
  'ExplorePageBTPInformationDeleteConfirmationButton': 'Eliminar',
  // settingspage
  'settingsPageAccountTitle': 'Cuenta',
  'settingsPageWalletBackupButton': 'Backup de la cartera',
  'settingsPageWalletBackupRestoreButton': 'Restaurar backup de la cartera',
  'settingsPageWalletDeleteButton': 'Eliminar cartera',
  'settingsPagePersonalizationTitle': 'Personalización',
  'settingsPageDarkModeButton': 'Modo oscuro',
  'settingsPageLanguageButton': 'Seleccionar idioma',
  // addBTP
  'appTopBarAddBTP': 'Añadir BTP',
  'addBTPSearchPlaceholder': 'Buscar un BTP...',
  'addBTPPageResults': 'Resultados',
  'addBTPPageOrder': 'Orden',
  'addBTPPageOrderByValue': 'Precio',
  'addBTPPageOrderByCedola': 'Cupón',
  'addBTPPageOrderByExpirationDate': 'Expiración',
  'addBTPPageOrderByValueButton': 'Precio de mercado',
  'addBTPPageOrderByCedolaButton': 'Cupón anual',
  'addBTPPageOrderByExpirationDateButton': 'Fecha de expiración',
  'addBTPPageFilterTitle': 'Personaliza tu búsqueda',
  'addBTPPageValueFilterTitle': 'Precio de mercado',
  'addBTPPageCedolaFilterTitle': 'Cupón anual',
  'addBTPPageExpirationDateFilterTitle': 'Expiración',
  'addBTPPageApplyFiltersButton': 'Aplicar',
  'addBTPPageDateSectionTitle': 'Fecha de compra',
  'addBTPPageSelectDateButton': 'Seleccionar',
  'addBTPPagePriceSectionTitle': 'Precio de compra (individual)',
  'addBTPPagePriceSectionPlaceholder': 'Precio de compra...',
  'addBTPPageInvestmentSectionTitle': 'Cantidad de BTP',
  'addBTPPageInvestmentSectionPlaceholder': '¿Cuántos BTPs?',
  'addBTPPageAddButton': 'Añadir a la cartera',
  'addBTPSecondPageBackButton': 'Seleccionar BTP',
};

Map<String, String> arabLang = {
  // misc
  'months': 'شهور',
  'and': 'و',
  'days': 'أيام',
  'cancel': 'إلغاء',
  'MyBTPInformationDeleteError': 'لحذف BTP ، انتقل إلى المحفظة.',
  'ExplorePageBTPInformationDeleteErrorButton': 'تجاهل',
  // header
  'appTopBarHome': 'simpleBTP',
  'appTopBarExplore': 'استكشاف',
  'appTopBarWallet': 'محفظة',
  'appTopBarSettings': 'الإعدادات',
  'appTopBarPickLanguage': 'اختر اللغة',
  // footer
  'appBottomBarHome': 'الصفحة الرئيسية',
  'appBottomBarExplore': 'استكشاف',
  'appBottomBarWallet': 'محفظة',
  'appBottomBarSettings': 'الإعدادات',
  // homepage
  'homeBalanceText': 'استثمارك',
  'homeMyAssets': 'أفضل BTP الخاصة بك',
  'homePageNoBTPsYet':
      "لم تقم بإضافة أي BTP بعد. انتقل إلى المحفظة لإضافة واحد.",
  'homeMyAssetsViewAllButton': 'عرض الكل',
  'homeBestBTPs': 'أفضل BTP',
  'homeBestBTPsViewAllButton': 'عرض الكل',
  // walletpage
  'walletBalanceText': 'استثمارك',
  'walletMyAssets': 'أصولك',
  'walletPaysWhat': 'يدفع',
  'walletPaysIn': 'في',
  'walletPageNoBTPsYet':
      'لإضافة أصل جديد ، اضغط على "+" في الزاوية العلوية اليمنى من الشاشة.',
  'walletBalanceGraphOneWeekText': 'أسبوع',
  'walletBalanceGraphOneMonthText': 'شهر',
  'walletBalanceGraphThreeMonthsText': '3M',
  'walletBalanceGraphOneYearText': 'سنة',
  'walletBalanceGraphTenYearsText': '10A',
  'WalletPageBTPInformationBuyDate': 'تاريخ الشراء',
  'WalletPageBTPInformationBuyPrice': 'سعر الشراء',
  'WalletPageBTPInformationProfitability': 'الربح عند الانتهاء',
  'WalletPageBTPInformationProfitabilityNow': 'الربح عند البيع الآن',
  'ExplorePageBTPInformationDeleteButton': 'حذف من المحفظة',
  // explorepage
  'exploreSearchPlaceholder': 'ابحث عن BTP...',
  'explorePageResults': 'النتائج',
  'explorePageOrder': 'طلب',
  'explorePageOrderByValue': 'السعر',
  'explorePageOrderByCedola': 'كوبون',
  'explorePageOrderByExpirationDate': 'انتهاء الصلاحية',
  'explorePageOrderByValueButton': 'سعر السوق',
  'explorePageOrderByCedolaButton': 'كوبون سنوي',
  'explorePageOrderByExpirationDateButton': 'تاريخ الانتهاء',
  'explorePageFilterTitle': 'تخصيص بحثك',
  'explorePageValueFilterTitle': 'سعر السوق',
  'explorePageCedolaFilterTitle': 'كوبون سنوي',
  'explorePageExpirationDateFilterTitle': 'تاريخ الانتهاء',
  'explorePageApplyFiltersButton': 'تطبيق',
  'ExplorePageBTPChartTitle': 'البيانات التاريخية',
  'ExplorePageBTPInformationTitle': 'معلومات BTP',
  'ExplorePageBTPInformationPrice': 'السعر',
  'ExplorePageBTPInformationCoupon': 'كوبون سنوي',
  'ExplorePageBTPInformationExpirationDate': 'تاريخ الانتهاء',
  'ExplorePageBTPInformationISIN': 'رمز ISIN',
  'ExplorePageBTPInformationProfitability': 'الربح عند الشراء الآن',
  'ExplorePageBTPInformationDeleteConfirmationMessage':
      'هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء.',
  'ExplorePageBTPInformationDeleteConfirmationCancelButton': 'إلغاء',
  'ExplorePageBTPInformationDeleteConfirmationButton': 'حذف',
  // settingspage
  'settingsPageAccountTitle': 'حساب',

  'settingsPageWalletBackupButton': 'نسخ احتياطي للمحفظة',
  'settingsPageWalletBackupRestoreButton': 'استعادة نسخة احتياطية للمحفظة',
  'settingsPageWalletDeleteButton': 'حذف المحفظة',
  'settingsPagePersonalizationTitle': 'تخصيص',
  'settingsPageDarkModeButton': 'الوضع الداكن',
  'settingsPageLanguageButton': 'اختر اللغة',
  // addBTP
  'appTopBarAddBTP': 'إضافة BTP',
  'addBTPSearchPlaceholder': 'ابحث عن BTP...',
  'addBTPPageResults': 'النتائج',
  'addBTPPageOrder': 'طلب',
  'addBTPPageOrderByValue': 'السعر',
  'addBTPPageOrderByCedola': 'كوبون',
  'addBTPPageOrderByExpirationDate': 'انتهاء الصلاحية',
  'addBTPPageOrderByValueButton': 'سعر السوق',
  'addBTPPageOrderByCedolaButton': 'كوبون سنوي',
  'addBTPPageOrderByExpirationDateButton': 'تاريخ الانتهاء',
  'addBTPPageFilterTitle': 'تخصيص بحثك',
  'addBTPPageValueFilterTitle': 'سعر السوق',
  'addBTPPageCedolaFilterTitle': 'كوبون سنوي',
  'addBTPPageExpirationDateFilterTitle': 'انتهاء الصلاحية',
  'addBTPPageApplyFiltersButton': 'تطبيق',
  'addBTPPageDateSectionTitle': 'تاريخ الشراء',
  'addBTPPageSelectDateButton': 'اختر',
  'addBTPPagePriceSectionTitle': 'سعر الشراء (فردي)',
  'addBTPPagePriceSectionPlaceholder': 'سعر الشراء...',
  'addBTPPageInvestmentSectionTitle': 'كمية BTP',
  'addBTPPageInvestmentSectionPlaceholder': 'كم BTP؟',
  'addBTPPageAddButton': 'إضافة إلى المحفظة',
  'addBTPSecondPageBackButton': 'اختر BTP',
};

Map<String, String> albanianLang = {
  // misc
  'months': 'muaj',
  'and': 'dhe',
  'days': 'ditë',
  'cancel': 'Anulo',
  'MyBTPInformationDeleteError': 'Për të fshirë një BTP, shkoni në Portofol.',
  'ExplorePageBTPInformationDeleteErrorButton': 'Heq dorë',
  // header
  'appTopBarHome': 'simpleBTP',
  'appTopBarExplore': 'Eksploro',
  'appTopBarWallet': 'Portofol',
  'appTopBarSettings': 'Cilësimet',
  'appTopBarPickLanguage': 'Zgjidhni gjuhën',
  // footer
  'appBottomBarHome': 'Kryefaqja',
  'appBottomBarExplore': 'Eksploro',
  'appBottomBarWallet': 'Portofol',
  'appBottomBarSettings': 'Cilësimet',
  // homepage
  'homeBalanceText': 'Investimi juaj',
  'homeMyAssets': 'BTP-të tuaja më të mira',
  'homePageNoBTPsYet':
      "Nuk keni shtuar ende asnjë BTP. Shkoni në Portofol për të shtuar një.",
  'homeMyAssetsViewAllButton': 'Shiko të gjitha',
  'homeBestBTPs': 'BTP-të më të mira',
  'homeBestBTPsViewAllButton': 'Shiko të gjitha',
  // walletpage
  'walletBalanceText': 'Investimi juaj',
  'walletMyAssets': 'Aktivet tuaja',
  'walletPaysWhat': 'Paguan',
  'walletPaysIn': 'në',
  'walletPageNoBTPsYet':
      'Për të shtuar një aktiv të ri, shtypni "+" në cepin e sipërm të djathtë të ekranit.',
  'walletBalanceGraphOneWeekText': 'Javë',
  'walletBalanceGraphOneMonthText': 'Muaj',
  'walletBalanceGraphThreeMonthsText': '3M',
  'walletBalanceGraphOneYearText': 'Vit',
  'walletBalanceGraphTenYearsText': '10V',
  'WalletPageBTPInformationBuyDate': 'Data e blerjes',
  'WalletPageBTPInformationBuyPrice': 'Çmimi i blerjes',
  'WalletPageBTPInformationProfitability': 'Fitimi në skadencë',
  'WalletPageBTPInformationProfitabilityNow': 'Fitimi duke shitur tani',
  'ExplorePageBTPInformationDeleteButton': 'Fshij nga portofoli',
  // explorepage
  'exploreSearchPlaceholder': 'Kërkoni për një BTP...',
  'explorePageResults': 'Rezultatet',
  'explorePageOrder': 'Rendit',
  'explorePageOrderByValue': 'Çmimi',
  'explorePageOrderByCedola': 'Kuponi',
  'explorePageOrderByExpirationDate': 'Skadimi',
  'explorePageOrderByValueButton': 'Çmimi i tregut',
  'explorePageOrderByCedolaButton': 'Kuponi vjetor',
  'explorePageOrderByExpirationDateButton': 'Data e skadimit',
  'explorePageFilterTitle': 'Personalizoni kërkimin tuaj',
  'explorePageValueFilterTitle': 'Çmimi i tregut',
  'explorePageCedolaFilterTitle': 'Kuponi vjetor',
  'explorePageExpirationDateFilterTitle': 'Data e skadimit',
  'explorePageApplyFiltersButton': 'Apliko',
  'ExplorePageBTPChartTitle': 'Të dhënat historike',
  'ExplorePageBTPInformationTitle': 'Informacioni BTP',
  'ExplorePageBTPInformationPrice': 'Çmimi',
  'ExplorePageBTPInformationCoupon': 'Kuponi vjetor',
  'ExplorePageBTPInformationExpirationDate': 'Data e skadimit',
  'ExplorePageBTPInformationISIN': 'Kodi ISIN',
  'ExplorePageBTPInformationProfitability': 'Fitimi duke blerë tani',
  'ExplorePageBTPInformationDeleteConfirmationMessage':
      'Jeni i sigurt? Ky veprim nuk mund të kthehet mbrapsht.',
  'ExplorePageBTPInformationDeleteConfirmationCancelButton': 'Anulo',
  'ExplorePageBTPInformationDeleteConfirmationButton': 'Fshij',
  // settingspage
  'settingsPageAccountTitle': 'Llogaria',
  'settingsPageWalletBackupButton': 'Backup i portofolit',
  'settingsPageWalletBackupRestoreButton': 'Rikthe backupin e portofolit',
  'settingsPageWalletDeleteButton': 'Fshij portofolin',
  'settingsPagePersonalizationTitle': 'Personalizimi',
  'settingsPageDarkModeButton': 'Mënyra e errët',
  'settingsPageLanguageButton': 'Zgjidhni gjuhën',
  // addBTP
  'appTopBarAddBTP': 'Shto BTP',
  'addBTPSearchPlaceholder': 'Kërkoni për një BTP...',
  'addBTPPageResults': 'Rezultatet',
  'addBTPPageOrder': 'Rendit',
  'addBTPPageOrderByValue': 'Çmimi',
  'addBTPPageOrderByCedola': 'Kuponi',
  'addBTPPageOrderByExpirationDate': 'Skadimi',
  'addBTPPageOrderByValueButton': 'Çmimi i tregut',
  'addBTPPageOrderByCedolaButton': 'Kuponi vjetor',
  'addBTPPageOrderByExpirationDateButton': 'Data e skadimit',
  'addBTPPageFilterTitle': 'Personalizoni kërkimin tuaj',
  'addBTPPageValueFilterTitle': 'Çmimi i tregut',
  'addBTPPageCedolaFilterTitle': 'Kuponi vjetor',
  'addBTPPageExpirationDateFilterTitle': 'Data e skadimit',
  'addBTPPageApplyFiltersButton': 'Apliko',
  'addBTPPageDateSectionTitle': 'Data e blerjes',
  'addBTPPageSelectDateButton': 'Zgjidh',
  'addBTPPagePriceSectionTitle': 'Çmimi i blerjes (i vetëm)',
  'addBTPPagePriceSectionPlaceholder': 'Çmimi i blerjes...',
  'addBTPPageInvestmentSectionTitle': 'Sasia e BTP',
  'addBTPPageInvestmentSectionPlaceholder': 'Sa BTP?',
  'addBTPPageAddButton': 'Shto në portofol',
  'addBTPSecondPageBackButton': 'Zgjidh BTP',
};
